In [17]:
import pandas as pd
import random

In [18]:
df = pd.read_excel('../Miel/Archivos-para-el-TP/Archivos para el TP/datos varios.xlsx', sheet_name='Consorcios')
df.head()

,Consorcio,Nombre del consorcio,Domicilio,Cant unidades funcionales,m2 totales
0,Consorcio 1,Azcuenaga,Belgrano 3344,30,1281
1,Consorcio 2,Alzaga,Callao 1122,20,914
2,Consorcio 3,Alberdi,Santa Fe 910,20,784
3,Consorcio 4,Unzue,Corrientes 5678,25,1316
4,Consorcio 5,Pereyra Iraola,Rivadavia 1234,40,1691

In [19]:
df['nro'] = df['Domicilio'].str.extract(r'(\d+)$').astype(float).astype('Int64')
df['calle'] = df['Domicilio'].str.replace(r'\s*\d+\s*$', '', regex=True)
df.head()

,Consorcio,Nombre del consorcio,Domicilio,Cant unidades funcionales,m2 totales,nro,calle
0,Consorcio 1,Azcuenaga,Belgrano 3344,30,1281,3344,Belgrano
1,Consorcio 2,Alzaga,Callao 1122,20,914,1122,Callao
2,Consorcio 3,Alberdi,Santa Fe 910,20,784,910,Santa Fe
3,Consorcio 4,Unzue,Corrientes 5678,25,1316,5678,Corrientes
4,Consorcio 5,Pereyra Iraola,Rivadavia 1234,40,1691,1234,Rivadavia

In [20]:
df['localidad'] = 'Ciudad Autónoma de Buenos Aires'
df['provincia'] = 'Ciudad Autónoma de Buenos Aires'
df['cuit'] = [f"30-{random.randint(10000000, 99999999)}-{random.randint(0,9)}" for _ in range(len(df))]
df['razon_social'] = df['Nombre del consorcio'] + " S.A."
bancos = ['Banco Nación', 'Banco Galicia', 'Banco BBVA', 'Banco Santander']
df['banco'] = [random.choice(bancos) for _ in range(len(df))]
df['cbu_cvu'] = [f"{random.randint(1000000000000000000000, 9999999999999999999999)}"[:22] for _ in range(len(df))]
df.head()

,Consorcio,Nombre del consorcio,Domicilio,Cant unidades funcionales,m2 totales,nro,calle,localidad,provincia,cuit,razon_social,banco,cbu_cvu
0,Consorcio 1,Azcuenaga,Belgrano 3344,30,1281,3344,Belgrano,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,30-14983792-8,Azcuenaga S.A.,Banco Galicia,9365951500885946727646
1,Consorcio 2,Alzaga,Callao 1122,20,914,1122,Callao,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,30-32488580-2,Alzaga S.A.,Banco Santander,8297092612365234621148
2,Consorcio 3,Alberdi,Santa Fe 910,20,784,910,Santa Fe,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,30-42207904-9,Alberdi S.A.,Banco BBVA,7311635356308676878583
3,Consorcio 4,Unzue,Corrientes 5678,25,1316,5678,Corrientes,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,30-64688988-1,Unzue S.A.,Banco Nación,6360527826027981935002
4,Consorcio 5,Pereyra Iraola,Rivadavia 1234,40,1691,1234,Rivadavia,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,30-62187934-7,Pereyra Iraola S.A.,Banco BBVA,4366445370937339953501

In [21]:
df.to_csv('./data/consorcios.csv', index=False, encoding='utf-8')